### PR TITLE
add support for timeouts

### PR DESCRIPTION
**Pull request by shaefner-usgs**

### CODE REVIEW

**Comment by shaefner-usgs** [comment]
It only uses the timeout if the user supplies on ontimeout method, and isn't used otherwise. Therefore, it seems like having a "smart" (non 0) default is better.

**Comment by jmfee-usgs** [comment]
It currently sets the timeout, but only sets the callback if the callback is defined.  It would work as you hope if you move setting the timeout property inside where it sets the callback...

**Comment by shaefner-usgs** [comment]
Ok, I did further testing, and you're correct...I didn't think the timeout property has any effect w/o the callback defined, but it does.

I updated the code as you suggested.

**Comment by jmfee-usgs** [comment]
Released to npm as 0.2.0
PR to add bundle to earthquake-website: https://github.com/usgs/earthquake-website/pull/1550

**Pull request merged**
